# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: >
          sudo apt-get update 
          && sudo apt-get install -y 
          build-essential
          python3.8
          uuid-dev
          iasl
          git
          gcc
          nasm
          python3-distutils
          gcc-arm-linux-gnueabi
          gcc-aarch64-linux-gnu
          gcc-riscv64-linux-gnu
          gcc-x86-64-linux-gnu
          && sudo apt-get clean
          && sudo ln -sf /usr/bin/python3.8 /usr/bin/python

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/tianocore/edk2.git
          submodules: recursive 
          path: edk2 

      # Runs a single command using the runners shell
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/tianocore/edk2-platforms.git
          submodules: recursive 
          path: edk2-platforms

      - uses: actions/checkout@v2
        with:
          repository: https://github.com/tianocore/edk2-non-osi.git
          submodules: recursive 
          path: edk2-non-osi

      - uses: actions/checkout@v2
        with:
          repository: https://github.com/IntelFsp/FSP.git
          submodules: recursive 
          path: FSP
      - run: cd edk2-platforms/Platform/Intel
      - run: python build_bios.py -p CometlakeURvp -t GCC5 -r
