# This is a basic workflow to help you get started with Actions

name: Build Intel platforms

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - 'README.md'
      - '_config.yml'
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: >
          sudo apt-get update
          && sudo apt-get install -y 
          build-essential
          python3.8
          uuid-dev
          iasl
          git
          gcc
          nasm
          python3-distutils
          gcc-arm-linux-gnueabi
          gcc-aarch64-linux-gnu
          gcc-riscv64-linux-gnu
          && sudo apt-get clean
          && sudo ln -sf /usr/bin/python3.8 /usr/bin/python

      # Use altername cmocka repo
      - run: git config --global url.https://github.com/neverware-mirrors/cmocka.git.insteadOf https://git.cryptomilk.org/projects/cmocka.git

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true 

      - run: git submodule foreach git submodule update --init --force --depth=1

      # Run the build commands
      - run: |
          cd edk2
          source ./edksetup.sh
          cd ..
          cd edk2-platforms/Platform/Intel
          python build_bios.py -p CometlakeURvp -t GCC5 -r

      - uses: actions/upload-artifact@v2
        with:
          name: CometlakeURvp_Release
          path: Build/CometlakeOpenBoardPkg/CometlakeURvp/RELEASE_GCC5/FV/COMETLAKEURVP.fd
