name: Fetch the latest source
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  submodule_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git submodule update --remote
          if ! git diff --exit-code --quiet; then
            git commit -am "$(date +"%Y-%m-%d")"
            git push
          fi
