name: Fetch the latest source
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  submodule_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git submodule update --remote 
          git diff --exit-code --quiet || (git commit -am "[CI] Update" && git push)
